services:
  trumproxy:
    build: .
    image: trumproxy-dev
    container_name: trumproxy-dev
    ports:
      - "6666:8080"
      - "51820:51820/udp"
      - "5000:5000"
    volumes:
      - ./app:/app
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
